In [3]:
import pandas as pd
import numpy as np

In [1]:
print("hello")

hello


In [9]:
# Display an array 

arr = [1,3,50,2,43]
arr = np.array(arr)
# arr.sort()
arr = np.sort(arr)
arr

array([ 1,  2,  3, 43, 50])

In [25]:
arr = [[1,2,3],
        [4,5,6]]
arr = np.array(arr)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# asort 
# type(arr)
arr.ndim
arr.shape



(2, 3)

In [29]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
# revrse function in numpy
arr = np.flip(arr)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr = np.zeros([3,3])
arr
# arr = np.ones(5)
# arr

# arr = np.eye(4)
# arr



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])